### ISSUE TITLE
Sorted projection

### ISSUE THREAD

**Issue by evanworley** [SteveSanderson/knockout-projections#1]
Any thoughts on how this library could be used or extended to provide a projection which sorts the items?

**Comment by jods4** [comment]
The new KO 3.0 `observableArray.subscribe(function() {}, 'arrayChange')` API is the building block that enables you to get efficient, incremental array changes notifications.

This library uses it to efficiently implement `filter` and `map` primitives.

Unfortunately, filter + map are not sufficient to implement a sort on top of them. So you would have to build your own optimized sort on top of the arrayChange feature.

Here's a sketch of how I would approach that: 
1. On the `sort` call, do a full array sort, which should be O(N log N); and subscribe to change notifications.
2. When an item is removed from the source array, remove it from the sorted array (O(log N) for a binary search, or O(1) if you saved the output index for each item somewhere -- but this is a O(N) memory trade-off).
3. When an item is added to the source array, perform an insertion into the sorted array by binary-searching its location. This is O(log N).
4. When the sorting key of an array item changes, I would suggest you remove it and insert it again, which would be O(log N).

BTW this library is an awesome starting point (thanks Steven), but it would be great if it could be extended to include an efficient implementation of all the standard array methods. I'm thinking of `sort`, `splice` (which enables an efficient top 10 results display), `reverse` and so on.

**Comment by SteveSanderson** [comment]
Great ideas. `sort` would be really nice to have here, but as you point out, it's far from trivial. There are many possible designs involving different tradeoffs. The best choice of tradeoff depends on the intended usage pattern (e.g., frequency of making large changes to the array vs inserting/removing individual items, and the cost of evaluating the comparison callback).

I would be interested to see if anyone wants to have a go at implementing `sort`.

**Comment by SteveSanderson** [comment]
As for `slice`, BTW, don't you think a simple computed observable would achieve this efficiently enough?

```
var topTen = ko.computed(function() {
    return someObservableArray().slice(0, 10);
});
```

Typically `slice` is pretty cheap, so I'm not sure how much would be gained in realistic cases by updating its output incrementally.

**Comment by jods4** [comment]
@SteveSanderson let's have the discussion about slice in issue #4 that I've opened about filter and index.

**Comment by evanworley** [comment]
I'd be happy to take a stab at sort. Will get back when I have something ready.

**Comment by SteveSanderson** [comment]
Great! I should clarify that I'm not in a position to take
non-Microsoft-originated pull requests into knockout-projections at the
moment (sorry!) so if you can implement "sort" then it could be distributed
either as a fork or as a separate plugin.

**Comment by evanworley** [comment]
Ouch! That's pretty unfortunate, as even a great implementation that's forked or a plugin would receive less traction by definition than something that was integrated into the core. What is the reason for such a restriction?

**Comment by SteveSanderson** [comment]
The way things are currently set up, it would require additional legal
review.

**Comment by SteveSanderson** [comment]
Closing this issue because there's no action to take on it at the moment, though we can still look at doing something relating to sorting in the future.

**Comment by sunesimonsen** [comment]
Just in case anybody is interested I implemented a sortBy projection in this fork: https://github.com/One-com/knockout-projections

**Comment by tp** [comment]
@sunesimonsen Thanks for the hint. I just noticed that your fork's sort method requires a different compare function parameter than Array.sort. Do you have any plan to support (a,b) => -1/0/1 style compare functions?

Or is this maybe back on the table for the main knockout-projection project?

**Comment by sunesimonsen** [comment]
@tp I don't have any use cases for a Array.sort like projection, but it would be interesting to see if it is possible to create one.
