### ISSUE TITLE
AMD / require.js support

### ISSUE THREAD

**Issue by zvolkov** [SteveSanderson/knockout-projections#15]
Please add support for loading knockout-projections as an AMD module. I would submit a pull request if license permitted.

**Comment by pksorensen** [comment]
It do not seem to work even though the code indicate that it support requirejs.

from my typescript files i load it like this but the filter function is not avalible on observable arrays. Could it be that it loads knockout twice and only add projections to the no imported ko?

```
/// <amd-dependency path="knockout.validation"/>
/// <amd-dependency path="knockout.projections"/> 
import ko = require('knockout');
import mapper = require('knockout.mapping');
```

**Comment by zvolkov** [comment]
@s093294 check out my fork: https://github.com/zvolkov/knockout-projections

**Comment by SteveSanderson** [comment]
Thanks for the suggestion. AMD support is now included.
