### ISSUE TITLE
bower.json not to explicitly specify knockout 3.1.0

### ISSUE THREAD

**Issue by layanto** [SteveSanderson/knockout-projections#25]
bower.json explicitly specifies knockout 3.1.0 preventing from using knockout 3.2.0 with bower.  Change bower.json dependency to >=3.1.0 instead?

**Comment by crissdev** [comment]
You may simply install `knockout` first and then `knockout-projections`. Not great but solves this issue.

``` sh
bower install knockout

# This will prompt you to choose the version you want to use
bower install knockout-projections
```
