### ISSUE TITLE
Filter: index in source array

### ISSUE THREAD

**Issue by jods4** [SteveSanderson/knockout-projections#4]
The callbacks signature are `map(item, index)` and `filter(item)`.

For map the index in the source array and result array are the same, so this one is easy.

I understand that filtering based on the output index may lead to unstable behavior and cascade effects, but is there any reason _not_ to provide the index in the _source_ array?

Sample use case: implementing an efficient top 10 filter becomes very easy.

**Comment by SteveSanderson** [comment]
Hey

You're right that filtering based on output index can produce unstable behavior! In fact it leads to pathologically bad  situations where the expense of recomputing the output grows wildly. That's exactly why this plugin doesn't allow the situation to occur.

Fortunately, achieving an efficient top-N filter based on input index is easy anyway:

```
this.topItems = ko.computed(function() {
    return this.items().slice(0, 10);
}, this);
```

... since using `slice` on an array is generally nice and fast.

As for passing the input index to `filter`, we could do this but it still leads to serious perf implications. If you add or remove items near the start of the array, the plugin would have to re-evaluate the filter predicate for _every_ subsequent item, which would clearly be at least `O(N)`. That basically breaks all the benefit of knockout-projections, and you might as well use a regular `ko.computed` as it would have the same perf characteristics.

Does that seem reasonable?

**Comment by jods4** [comment]
First of all, I have to admit that not many useful use cases for filtering on source index come to mind. Top/Bottom X is the only obvious one. Sometimes I also build a column layout by creating a few subsets [0-10], [11-20], [21-30] that are bound in different columns in UI, but this is mostly the same thing (and will be handled by CSS in the future).

So maybe (?) there are not enough use cases to justify the change.

Now about the change itself: I picture `index` as an observable (as is the case with `map`). This means that only filters that read it would pay the cost. 
I agree inserting at index 0 means N recomputations. On the other hand, your amortized performance may be a lot better, depending on the distribution of your inserts. E.g. if you insert/remove mostly at the end, or even in a uniformly random way.

There is a second performance benefit, which also applies to your `slice` example, so let's discuss using `slice` as a top 10 filter.

Yes, `slice` itself is quite efficient -- at least as long as N in "top N" stays relatively small. Taking the first 1000 elements of a huge array, less so (is it useful? I don't know, maybe not).

But don't forget to consider what happens _with the result of the computed_. More often than not it's going to be bound to some UI. Maybe some expensive templated list. If I do a "top 100", the `slice` might be fast, but _everytime an element is appended to the source list, the whole UI is re-created_. Imagine I'm appending 30 new elements in a loop... because KO is synchronous, that's a _lot_ of useless DOM operations.

On the other hand, with a smarter top 100 implementation, appending an item to the source array could easily be a no-op.

Not sure about the cost vs benefit ratio of all this. What do you think?

**Comment by jrsearles** [comment]
I was looking for a way to accomplish an efficient Top N select and was also initially looking to use this filter projection. I ended up going a different route though when i realised it'd be fairly trivial to prevent unnecessary updates by examining the array changes and ignoring them when they don't apply to the given slice. Here is what i came up with. (I'm a bit of a Knockout newb so there may be better ways to accomplish this.

```
ko.observableArray.fn.observableSlice = function(begin, end) {
    var self = this;
    var newArray = ko.observableArray(self.peek().slice(begin, end));

    self.subscribe(function(changes) {
        var endingIndex = end;
        var underlyingArray = self.peek();
        // note: if no arguments are passed in, the result is the entire array so always notify
        var hasUpdates = begin === undefined;

        // need to account for no ending index or negative ending index
        if (endingIndex === undefined) {
            endingIndex = underlyingArray.length;
        } else if (endingIndex < 0) {
            endingIndex += underlyingArray.length + 1;
        }

        if (!hasUpdates) {
            hasUpdates = changes.some(function (change) {
                return change.index >= begin && change.index < endingIndex;
            });
        }   

        if (hasUpdates) {
            newArray(underlyingArray.slice(begin, end));
        }
    }, null, "arrayChange");

    return ko.computed({
        read: newArray
    });
};
```

**Comment by SteveSanderson** [comment]
@jrsearles - agreed - that looks good!

I'll close this since it isn't something that needs to be solved inside KO-projections, but rather works nicely as a utility function in your app or even a separate plugin.
