### ISSUE TITLE
More functions: aggregates

### ISSUE THREAD

**Issue by Igorbek** [SteveSanderson/knockout-projections#5]
Also will be great to have aggregate functions:

``` js
var observableArrayOfStrings; // KnockoutObservableArray<string>
var result = observableArrayOfStrings.aggregate(
  0, // seed
  function (acc, val) { // func to add to accamulator
    return acc + val.length; },
  function (acc, val) { // func to remove from accamulator
    return acc - val.length; });
var observableSum =
  ko.observableArray([1, 0, 17, -2, 3])
  .sum();
```

Functions can be:
- aggregate - base aggregate functions
- sum
- min (need to recalculate if removed value is current min)
- max (same as min)

**Comment by SteveSanderson** [comment]
That's interesting. It would get a bit more complex still though as the individual items can observably change value, so you'd have to recalculate the min/max if the current min/max gets larger/smaller. Then there's the question of whether you cache a reference to the second-biggest/smallest to speed that up, and the third biggest-smallest to speed up recalculating that, etc. :) Eventually you just want an observably sorted list.

If you want to have a go at implementing this separately it will be interesting to see how it works out, but I'll close this issue now as it's not something I'm planning to include in KO-projections in the short term.

**Comment by Igorbek** [comment]
I can do it by myself as PR. Is it ok?

**Comment by SteveSanderson** [comment]
I'm afraid as per
https://github.com/SteveSanderson/knockout-projections/blob/master/CONTRIBUTING.md, this plugin
is not currently able to take pull requests, so you'll need to keep
the feature in a separate fork. Sorry about this awkwardness!
