### ISSUE TITLE
Create a NuGet package

### ISSUE THREAD

**Issue by mgrosperrin** [SteveSanderson/knockout-projections#6]
Hello,

could you create a NuGet package of your plugin ?

Thanks

**Comment by SteveSanderson** [comment]
Done. Thanks for the suggestion!

**Comment by mgrosperrin** [comment]
Hi Steve,
I have seen you have created the package.nuspec, with the Id knockout-projections. Unfortunately, I am not able to find it on nuget.org. Where have you published the package ?
Thanks.

**Comment by spring1975** [comment]
I'm also not seeing it show up in a nuget search in VS.  Do you have the package manager command?  I've tried the following and got an error saying it doesn't exist.
PM> Install-Package knockout-projections

**Comment by jcmcbeth** [comment]
@SteveSanderson I am also unable to find this package through nuget. Is this an active issue or am I doing something wrong?
