### ISSUE TITLE
Working with ko.computed

### ISSUE THREAD

**Issue by brianmhunt** [SteveSanderson/knockout-projections#9]
It would seem that the functions this plugin provides (`.map` and `.filter`) are not added to `ko.computed`, however I was wondering: How difficult would it be to make such work?

Just curious.

Cheers.

**Comment by SteveSanderson** [comment]
Computed properties don't natively raise `arrayChange` notifications, so KO-projections wouldn't be able to detect their changes efficiently. However you can pipe an array-valued computed property into a real `ko.observableArray` and then use the `map`/`filter` functions on it, e.g.:

```
var myObservableArray = ko.observableArray(myArrayValuedComputed());
myArrayValuedComputed.subscribe(myObservableArray);
```

Now `myObservableArray` is a real observable array (so you can `map`/`filter` it), and it will be updated whenever `myArrayValuedComputed` changes.

**Comment by brianmhunt** [comment]
Thank you, Steve. That is a helpful suggestion. Cheers.
